title: Taylor Collard
logo: "/images/headshot_circle.jpeg"
description: >
  Recently separated Air Force veteran with 6 years of analytical experience. 
  <br><br>
  Foundational coursework training through Google and IMB data analysis certifications.
  <br><br>
  <a href="https://www.linkedin.com/in/taylor-collard/">View My LinkedIn Profile</a>
  
#show_downloads: true
theme: jekyll-theme-minimal
