title: Taylor Collard
logo: /images/headshot_circle.png
description: >
  Recently separated Air Force veteran with 6 years of analytical experience. Foundational coursework training through Google and IMB data analysis certifications.
#show_downloads: true
theme: jekyll-theme-minimal
